import type {Metadata} from "next";

import "./globals.css";
import {font} from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Moviefy | ",
  description: "Generated by Samuel Perez Martinez",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={`${font.className} dark h-full bg-background antialiased`}>{children}</body>
    </html>
  );
}
