import type {Metadata} from "next";

import {Toaster} from "sonner";

import "./globals.css";
import {font} from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Moviefy | ",
  description: "Generated by Samuel Perez Martinez",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={`${font.className} dark h-full bg-background antialiased`}>
        {children}
        <Toaster closeButton richColors />
      </body>
    </html>
  );
}
