import type {Metadata} from "next";

import "./globals.css";
import {font} from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Moviefy | ",
  description: "Generated by Samuel Perez Martinez",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={`${font.className} dark container bg-background antialiased`}>
        <main className="py-8">{children}</main>
        <footer className="text-center leading-[4rem] opacity-70">
          © {new Date().getFullYear()} movies-app
        </footer>
      </body>
    </html>
  );
}
